services:
  postgres:
    image: postgres:16-alpine
    container_name: studio45-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studio45
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d studio45"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - studio45-network

volumes:
  postgres_data:
    driver: local

networks:
  studio45-network:
    driver: bridge
